#!/usr/bin/python3

"""GuanoDoc: the batshit insane document system"""

import sys
from argparse import ArgumentParser
import re

def main(args):
	parser = ArgumentParser(
		prog='guano',
		description="The batshit insane document system."
	)
	parser.add_argument(
		'source',
		metavar='SOURCE',
		help='document source file'
	)
	args = parser.parse_args(args)
	
	# Read from file or stdin if '-' specified.
	if (args.source == '-'):
		source_file = sys.stdin
	else:
		source_file = open(args.source)
	
	try:
		# Pass input through verbatim for now.
		parse(source_file, sys.stdout)
	finally:
		if source_file != sys.stdin:
			source_file.close()

def parse(stream, out):
	for line in stream:
		if re.match('#.*', line):
			# Ignore comment.
			continue
		match = re.match('@parser (\w+)', line)
		if match:
			parser_name = match.group(1)
			globals()[parser_name](stream, out)
			continue
		# Pass everything else through verbatim.
		out.writelines(line)

# Sample alternative parser.
def block_quoter(stream, out):
	for line in stream:
		if line == '<\n':
			return
		else:
			out.writelines("> " + line)

if __name__ == '__main__':
	sys.exit(main(sys.argv[1:]))
