#!/usr/bin/python3

"""GuanoDoc: the batshit insane document system"""

import sys
from argparse import ArgumentParser
import parsers

def main(args):
	arg_parser = ArgumentParser(
		prog='guano',
		description="The batshit insane document system."
	)
	arg_parser.add_argument(
		'source',
		metavar='SOURCE',
		help='document source file'
	)
	args = arg_parser.parse_args(args)
	
	# Read from file or stdin if '-' specified.
	if (args.source == '-'):
		source_file = sys.stdin
	else:
		source_file = open(args.source)
	
	try:
		# This may delegate to other specialised parsers.
		parsers.parse(source_file, sys.stdout)
	finally:
		if source_file != sys.stdin:
			source_file.close()

if __name__ == '__main__':
	sys.exit(main(sys.argv[1:]))
