#!/bin/sh -e

if [ "$(id -u)" != "0" ]; then
	echo "This script must be run as root." >&2
	exit 1
fi

# Require Python and `pip' to be available.

available() {
	command -v "$1" >/dev/null 2>&1
}

if available pip; then
	pip install markdown
elif available pip-python3; then
	pip-python3 install markdown
elif available pip-3.2; then
	pip-3.2 install markdown
else
	echo "You need to install \`pip' for Python 3." >&2
	exit 1
fi
